#
# Makefile for imx mcc
#
#
obj-$(CONFIG_IMX_SEMA4)		+= imx_sema4.o
obj-$(CONFIG_IMX_MCC_TEST)	+= imx_mcc_test.o
obj-$(CONFIG_IMX_M4_DEBUGGER)	+= m4_udooneo_debugger.o
obj-$(CONFIG_IMX_MCC_TTY)	+= m4_udooneo_debugger.o

