#
# Makefile for Freescale fxos8700 and fxas2100x drivers
# Freescale FXOS8700   - Digital Sensor - 3D Accelerometer (±2g/±4g/±8g) + 3D Magnetometer
# Freescale FXAS21002C - Freescale 3-Axis Digital Gyroscope
#
obj-$(CONFIG_FXOS8700_ACC_MAG_I2C) 		+= fxos8700.o
obj-$(CONFIG_FXAS2100X_GYRO_I2C) 		+= fxas2100x.o
